# Generated by Django 5.1.5 on 2025-01-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_content', models.TextField()),
                ('schedduled_time', models.DateTimeField()),
                ('platform', models.CharField(choices=[('Twitter', 'Twitter'), ('TikTok', 'TikTok'), ('Instagram', 'Instagram')], max_length=50)),
                ('is_posted', models.BooleanField(default=False)),
            ],
        ),
    ]
