# Generated by Django 5.1.5 on 2025-02-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_posttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttemplate',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'Tiktok'), ('twitter', 'Twitter')], default='instagram', max_length=20),
        ),
    ]
