# Generated by Django 5.1.5 on 2025-02-03 22:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_posttemplate_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='scheduled_time',
        ),
        migrations.AddField(
            model_name='post',
            name='platform',
            field=models.CharField(choices=[('Instagram', 'Instagram'), ('TikTok', 'TikTok'), ('Twitter', 'Twitter')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
    ]
