# Generated by Django 5.1.5 on 2025-02-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_remove_post_created_at_remove_post_scheduled_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, help_text='Select a scheduled posting time. Leave blank for immediate posting.', null=True),
        ),
    ]
